Dev
Ashishgupta08/video-library pull request #1
Opened 2021-05-06 18:26 UTC by Ashishgupta08

### Video-Library App

You can check the live demo of the app [here](https://learnit-app.netlify.app/).

Please give your valuable feedback to enhance this project.

ThankYou!!!

2021-05-08 10:52 UTC, Akshay-Laxmipathi commented
Your add to playlist button in the individual video pages is not working.

2021-05-09 17:47 UTC, JatinRanka requested changes

2021-05-09 17:47 UTC, JatinRanka commented on src/Pages/VideoPlayer/VideoPlayer.jsx
> +                            <MdWatchLater className={watchLater} onClick={()=>{addToWatchLater(video)}} />
Increase icon size

2021-05-09 17:47 UTC, JatinRanka commented on src/Pages/Home/Home.jsx
>                      videoData.map(item => <VideoCard data={item} />)
Add key

2021-05-09 17:47 UTC, JatinRanka commented on src/Pages/Playlist/Playlist.jsx
> +import { usePlaylist } from "../../Contexts/playlist-context";
use index file for importing

2021-05-09 19:54 UTC, Ashishgupta08 commented on src/Pages/Home/Home.jsx
>                      videoData.map(item => <VideoCard data={item} />)
Done

2021-05-09 19:57 UTC, Ashishgupta08 commented on src/Pages/Playlist/Playlist.jsx
> +import { usePlaylist } from "../../Contexts/playlist-context";
Done

2021-05-09 20:06 UTC, Ashishgupta08 commented on src/Pages/VideoPlayer/VideoPlayer.jsx
> +                            <MdWatchLater className={watchLater} onClick={()=>{addToWatchLater(video)}} />
Done

2021-06-25 21:55 UTC, closed without merging